$(document).on("click", "#photo_of_man1", function () {
    $("#photo_of_man1").css({border: "thick double #32a1ce"})
    $("#photo_of_man2").css({border: "thick double #32a1ce00"})
    $("#photo_of_women1").css({border: "thick double #32a1ce00"})
    $("#photo_of_women2").css({border: "thick double #32a1ce00"})
    $("#text_about").hide()
    $("#text_about_man1").show()
    $("#text_about_man2").hide()
    $("#text_about_women1").hide()
    $("#text_about_women2").hide()
})
$(document).on("click", "#photo_of_man2", function () {
    $("#photo_of_man1").css({border: "thick double #32a1ce00"})
    $("#photo_of_man2").css({border: "thick double #32a1ce"})
    $("#photo_of_women1").css({border: "thick double #32a1ce00"})
    $("#photo_of_women2").css({border: "thick double #32a1ce00"})
    $("#text_about").hide()
    $("#text_about_man1").hide()
    $("#text_about_man2").show()
    $("#text_about_women1").hide()
    $("#text_about_women2").hide()
})
$(document).on("click", "#photo_of_women1", function () {
    $("#photo_of_man1").css({border: "thick double #32a1ce00"})
    $("#photo_of_man2").css({border: "thick double #32a1ce00"})
    $("#photo_of_women1").css({border: "thick double #32a1ce"})
    $("#photo_of_women2").css({border: "thick double #32a1ce00"})
    $("#text_about").hide()
    $("#text_about_man1").hide()
    $("#text_about_man2").hide()
    $("#text_about_women1").show()
    $("#text_about_women2").hide()
})
$(document).on("click", "#photo_of_women2", function () {
    $("#photo_of_man1").css({border: "thick double #32a1ce00"})
    $("#photo_of_man2").css({border: "thick double #32a1ce00"})
    $("#photo_of_women1").css({border: "thick double #32a1ce00"})
    $("#photo_of_women2").css({border: "thick double #32a1ce"})
    $("#photo_of_studio").css({border: "thick double #32a1ce"})
    $("#text_about").hide()
    $("#text_about_man1").hide()
    $("#text_about_man2").hide()
    $("#text_about_women1").hide()
    $("#text_about_women2").show()
})
$(document).on("click", "#photo_of_studio", function () {
    $("#photo_of_man1").css({border: "thick double #32a1ce00"})
    $("#photo_of_man2").css({border: "thick double #32a1ce00"})
    $("#photo_of_women1").css({border: "thick double #32a1ce00"})
    $("#photo_of_women2").css({border: "thick double #32a1ce00"})
    $("#photo_of_studio").css({border: "thick double #32a1ce"})
    $("#text_about").show()
    $("#text_about_man1").hide()
    $("#text_about_man2").hide()
    $("#text_about_women1").hide()
    $("#text_about_women2").hide()
})