css_when_click = { border: "2px dotted #fff", "box-shadow": "12px 12px 12px 12px rgba(0, 0, 0, .2)" }
css_when_dont_click = { border: "2px dotted #ffffff00", "box-shadow": "12px 12px 12px 12px rgba(0, 0, 0,0)" }


$(document).on("click", "#photo_of_man1", function () {
    $("#photo_of_man1").css(css_when_click)
    $("#photo_of_man2").css(css_when_dont_click)
    $("#photo_of_women1").css(css_when_dont_click)
    $("#photo_of_women2").css(css_when_dont_click)
    $("#photo_of_studio").css(css_when_dont_click)
    $("#text_about").hide()
    $("#text_about_man1").show()
    $("#text_about_man2").hide()
    $("#text_about_women1").hide()
    $("#text_about_women2").hide()
})
$(document).on("click", "#photo_of_man2", function () {
    $("#photo_of_man1").css(css_when_dont_click)
    $("#photo_of_man2").css(css_when_click)
    $("#photo_of_women1").css(css_when_dont_click)
    $("#photo_of_women2").css(css_when_dont_click)
    $("#photo_of_studio").css(css_when_dont_click)
    $("#text_about").hide()
    $("#text_about_man1").hide()
    $("#text_about_man2").show()
    $("#text_about_women1").hide()
    $("#text_about_women2").hide()
})
$(document).on("click", "#photo_of_women1", function () {
    $("#photo_of_man1").css(css_when_dont_click)
    $("#photo_of_man2").css(css_when_dont_click)
    $("#photo_of_women1").css(css_when_click)
    $("#photo_of_women2").css(css_when_dont_click)
    $("#photo_of_studio").css(css_when_dont_click)
    $("#text_about").hide()
    $("#text_about_man1").hide()
    $("#text_about_man2").hide()
    $("#text_about_women1").show()
    $("#text_about_women2").hide()
})
$(document).on("click", "#photo_of_women2", function () {
    $("#photo_of_man1").css(css_when_dont_click)
    $("#photo_of_man2").css(css_when_dont_click)
    $("#photo_of_women1").css(css_when_dont_click)
    $("#photo_of_women2").css(css_when_click)
    $("#photo_of_studio").css(css_when_dont_click)
    $("#text_about").hide()
    $("#text_about_man1").hide()
    $("#text_about_man2").hide()
    $("#text_about_women1").hide()
    $("#text_about_women2").show()
})
$(document).on("click", "#photo_of_studio", function () {
    $("#photo_of_man1").css(css_when_dont_click)
    $("#photo_of_man2").css(css_when_dont_click)
    $("#photo_of_women1").css(css_when_dont_click)
    $("#photo_of_women2").css(css_when_dont_click)
    $("#photo_of_studio").css(css_when_click)
    $("#text_about").show()
    $("#text_about_man1").hide()
    $("#text_about_man2").hide()
    $("#text_about_women1").hide()
    $("#text_about_women2").hide()
})